login: &login
  adapter: postgresql
  encoding: utf8
  username: nico
  password:
#  host: localhost
#  socket: /var/run/mysqld/mysql.sock

development:
  <<: *login
  database: transfair_development

test:
  <<: *login
  database: transfair_test

production:
  <<: *login
  database: app_prod
